services:

  ros-interface:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros-interface
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      DT_LAUNCHER: default
      DT_SUPERUSER: 1
      DT_CAMERA_SHM_IN_PATH: ${DT_CAMERA_SHM_IN_PATH:-/dtps-shm/front_center}
      DT_CAMERA_SHM_ONLY_JPEG: ${DT_CAMERA_SHM_ONLY_JPEG:-0}
      DT_CAMERA_SHM_ONLY_INFO: ${DT_CAMERA_SHM_ONLY_INFO:-0}
      DT_CAMERA_SHM_ONLY_PARAMETERS: ${DT_CAMERA_SHM_ONLY_PARAMETERS:-0}
    volumes:
      - /data/ramdisk:/data/ramdisk
      - camera-shm:/dtps-shm
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data/config/robot_hardware:/data/config/robot_hardware:ro

  rosbridge-websocket:
    image: ${REGISTRY}/duckietown/dt-rosbridge-websocket:ente-${ARCH}
    container_name: ros1-rosbridge-websocket
    restart: unless-stopped
    network_mode: host
    environment:
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  car-interface:
    image: ${REGISTRY}/duckietown/dt-core:ente-${ARCH}
    container_name: car-interface
    restart: always
    network_mode: host
    environment:
      DT_SUPERUSER: 1
    volumes:
      - /data:/data
      # dtps sockets
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

volumes:
  camera-shm:
    external: true
    name: ${DT_CAMERA_SHM_VOLUME:-duckietown-camera-shm}
