services:

  ros-interface:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros-interface
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      DT_LAUNCHER: default
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data/config/robot_hardware:/data/config/robot_hardware:ro

  rosbridge-websocket:
    image: ${REGISTRY}/duckietown/dt-rosbridge-websocket:ente-${ARCH}
    container_name: ros1-rosbridge-websocket
    restart: unless-stopped
    network_mode: host
    environment:
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  car-interface:
    image: ${REGISTRY}/duckietown/dt-core:ente-${ARCH}
    container_name: car-interface
    restart: always
    network_mode: host
    environment:
      DT_SUPERUSER: 1
    volumes:
      - /data:/data
      # dtps sockets
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
