services:

  ros-interface:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros-interface
    restart: unless-stopped
    network_mode: host
    privileged: true
    pid: host
    environment:
      DT_LAUNCHER: default
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data

  rosbridge-websocket:
    image: ${REGISTRY}/duckietown/dt-rosbridge-websocket:ente-${ARCH}
    container_name: ros1-rosbridge-websocket
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data

  fly_commands_mux:
    image: ${REGISTRY}/duckietown/dt-core:ente-${ARCH}
    container_name: fly_commands_mux
    restart: unless-stopped
    network_mode: host
    environment:
      DT_SUPERUSER: 1
      DT_LAUNCHER: default-duckiedrone
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data
