version: '3.2'
services:

  # Driver nodes
  camera:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros1-camera
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      DT_LAUNCHER: sensor-camera
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data

  tof:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros1-tof
    restart: unless-stopped
    network_mode: host
    environment:
      DT_SUPERUSER: 1
      DT_LAUNCHER: sensor-tof
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data

  imu:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros1-imu
    restart: unless-stopped
    network_mode: host
    environment:
      DT_SUPERUSER: 1
      DT_LAUNCHER: sensor-imu
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data

  flight-controller:
    image: ${REGISTRY}/duckietown/dt-ros-interface:ente-${ARCH}
    container_name: ros1-flight-controller
    restart: unless-stopped
    network_mode: host
    environment:
      DT_SUPERUSER: 1
      DT_LAUNCHER: actuator-flight-controller
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data

  # Master node
  ros:
    image: ${REGISTRY}/duckietown/dt-ros-commons:ente-${ARCH}
    container_name: ros1
    restart: unless-stopped
    network_mode: host
    volumes:
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data
  
  rosbridge-websocket:
    image: ${REGISTRY}/duckietown/dt-rosbridge-websocket:ente-${ARCH}
    container_name: ros1-rosbridge-websocket
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data

  # Functionalities nodes
  altitude:
    image: ${REGISTRY}/duckietown/dt-core:ente-${ARCH}
    container_name: altitude
    restart: unless-stopped
    network_mode: host
    environment:
      DT_SUPERUSER: 1
      DT_LAUNCHER: duckiedrone-altitude-node
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data

    # Functionalities nodes
  fly_commands_mux:
    image: ${REGISTRY}/duckietown/dt-core:ente-${ARCH}
    container_name: fly_commands_mux
    restart: unless-stopped
    network_mode: host
    environment:
      DT_SUPERUSER: 1
      DT_LAUNCHER: default-duckiedrone
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data