version: '3.2'
services:

  portainer:
    image: docker.io/portainer/portainer:1.24.1-alpine
    container_name: portainer
    command: ["--host=unix:///var/run/docker.sock", "--no-auth"]
    restart: always
    network_mode: host
    volumes:
      - portainer-data:/data
      # docker socket
      - /var/run/docker.sock:/var/run/docker.sock

  dashboard:
    image: ${REGISTRY}/duckietown/dt-device-dashboard:daffy-${ARCH}
    container_name: dashboard
    restart: unless-stopped
    network_mode: host
    environment:
      HTTP_PORT: 8080
    volumes:
      - /data:/data
      - /secrets:/secrets
      # compose volume
      - compose-data:/user-data/databases
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  files-api:
    image: ${REGISTRY}/duckietown/dt-files-api:daffy-${ARCH}
    container_name: files-api
    restart: always
    network_mode: host
    volumes:
      - /data:/data
      - /secrets:/secrets
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  code-api:
    image: ${REGISTRY}/duckietown/dt-code-api:daffy-${ARCH}
    container_name: code-api
    restart: always
    network_mode: host
    volumes:
      - /data:/data
      - /code:/user_code
      # docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  device-proxy:
    image: ${REGISTRY}/duckietown/dt-device-proxy:daffy-${ARCH}
    container_name: device-proxy
    restart: always
    network_mode: host
    volumes:
      - /data:/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  device-health:
    image: ${REGISTRY}/duckietown/dt-device-health:daffy-${ARCH}
    container_name: device-health
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /data:/data
      - /triggers:/triggers
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  device-online:
    image: ${REGISTRY}/duckietown/dt-device-online:daffy-${ARCH}
    container_name: device-online
    restart: always
    network_mode: host
    volumes:
      - /data:/data
      - /secrets:/secrets
      # docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  ros:
    image: ${REGISTRY}/duckietown/dt-ros-commons:daffy-${ARCH}
    container_name: ros
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data:/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  duckiebot-interface:
    image: ${REGISTRY}/duckietown/dt-duckiebot-interface:daffy-${ARCH}
    container_name: duckiebot-interface
    restart: unless-stopped
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - /data:/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      # nvargus socket
      - /tmp:/tmp

  car-interface:
    image: ${REGISTRY}/duckietown/dt-car-interface:daffy-${ARCH}
    container_name: car-interface
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data:/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  rosbridge-websocket:
    image: ${REGISTRY}/duckietown/dt-rosbridge-websocket:daffy-${ARCH}
    container_name: rosbridge-websocket
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data:/data
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

volumes:
  compose-data:
  portainer-data:
