version: '3'
services:

  duckietown-swarm:
    image: duckietown/duckietown-swarm-rpi:latest
    restart: unless-stopped
    network_mode: host
    environment:
      DISABLE_CONTRACTS: 1
    volumes:
      - ipfs-storage:/ipfs-storage
    command: dt-swarm daemon --low-power --ipfs-dir /ipfs-storage

volumes:
  ipfs-storage:
