version: '3'
services:

  http-server:
    image: duckietown/rpi-simple-server:master18
    restart: always
    network_mode: "host"
    volumes:
    - "/data:/data"
    working_dir: /data

  rpi-health:
    image: duckietown/rpi-health:master18
    restart: always
    network_mode: "host"
    devices:
    - "/dev/vchiq:/dev/vchiq"

