version: '3'
services:

  rpi-simple-server:
    image: duckietown/rpi-simple-server:master18
    restart: always
    network_mode: "host"
    volumes:
    - "/data:/data"
    working_dir: /data

  rpi-health:
    image: duckietown/rpi-health:master18
    restart: always
    network_mode: "host"
    devices:
    - "/dev/vchiq:/dev/vchiq"

  rpi-duckiebot-online:
    image: duckietown/rpi-duckiebot-online:master18
    restart: always
    network_mode: "host"
    volumes:
    - "/data:/data"
    - "/secrets:/secrets"
    - "/var/local:/var/local"

  rpi-duckiebot-loader:
    image: duckietown/rpi-duckiebot-loader:master18
    restart: always
    network_mode: "host"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/data:/data"
    - "/secrets:/secrets"
    - "/var/local:/var/local"

