version: '3'
services:

    roscore:
        image: duckietown/rpi-ros-kinetic-roscore:master18
        restart: unless-stopped
        network_mode: host
        ports: # this is redundant if network_mode = host
        - "11311:11311"
        environment:
          DISABLE_CONTRACTS: 1
