services:

  zenoh-router:
    image: ${REGISTRY}/duckietown/dt-ros2-commons:ente-${ARCH}
    container_name: zenoh-router
    command: ["bash", "-c", ". /opt/ros/jazzy/setup.bash && ros2 run rmw_zenoh_cpp rmw_zenohd"]
    restart: unless-stopped
    network_mode: host
    environment:
      ZENOH_ROUTER_ID: duckiedrone_router
      ROS_DOMAIN_ID: 42

  camera:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-camera
    restart: unless-stopped
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: sensor-camera-rpi
      DT_SUPERUSER: 1
      ROS_DOMAIN_ID: 42
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  tof-bottom:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-tof-bottom
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: sensor-tof-bottom
      DT_SUPERUSER: 1
      ROS_DOMAIN_ID: 42
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  mavros:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-mavros
    restart: unless-stopped
    network_mode: host
    privileged: true
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: mavros
      DT_SUPERUSER: 1
      ROS_DOMAIN_ID: 42
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /data:/data
    depends_on:
      - zenoh-router

  foxglove-bridge:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-foxglove-bridge
    restart: unless-stopped
    network_mode: host
    command: ["bash", "-c", ". /opt/ros/jazzy/setup.bash && ros2 launch foxglove_bridge foxglove_bridge_launch.xml"]
    environment:
      ROS_DOMAIN_ID: 42
      RMW_IMPLEMENTATION: rmw_zenoh_cpp
    depends_on:
      - zenoh-router

  rosbridge-websocket:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-rosbridge-websocket
    restart: unless-stopped
    network_mode: host
    environment:
      DT_SUPERUSER: 1
      ROS_DOMAIN_ID: 42
      DT_LAUNCHER: rosbridge
    volumes:
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  # Functionalities nodes
  
