services:

  zenoh-router:
    image: ${REGISTRY}/duckietown/dt-ros2-commons:ente-${ARCH}
    container_name: zenoh-router
    command: ["bash", "-c", ". /opt/ros/jazzy/setup.bash && ros2 run rmw_zenoh_cpp rmw_zenohd"]
    restart: unless-stopped
    network_mode: host
    environment:
      ZENOH_ROUTER_ID: duckiebot_router

  camera:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-camera
    restart: unless-stopped
    network_mode: host
    pid: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: sensor-camera
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  tof:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-tof
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: sensor-tof
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  imu:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-imu
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: sensor-imu
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  power-button:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-power-button
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: sensor-power-button
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  wheel-encoders:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-wheel-encoders
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: sensor-wheel-encoders
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  wheels:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-wheels
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: actuator-wheels
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  leds:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-leds
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: actuator-leds
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  display:
    image: ${REGISTRY}/duckietown/dt-ros2-interface:ente-${ARCH}
    container_name: ros2-display
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_LAUNCHER: actuator-display
      DT_SUPERUSER: 1
    volumes:
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router

  # rosbridge-websocket:
  #   image: ${REGISTRY}/duckietown/dt-ros2bridge-websocket:ente-${ARCH}
  #   container_name: ros2-rosbridge-websocket
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     DT_SUPERUSER: 1
  #   volumes:
  #     - /data/ramdisk/dtps:/dtps
  #     # avahi socket
  #     - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  car-interface:
    image: ${REGISTRY}/duckietown/dt-core:ente-${ARCH}
    container_name: car-interface
    restart: always
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DT_SUPERUSER: 1
    volumes:
      - /data:/data
      # dtps sockets
      - /data/ramdisk/dtps:/dtps
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    depends_on:
      - zenoh-router
